### ISSUE TITLE
There seems to be a bug, postman's cURL does not support

### ISSUE THREAD

**Issue by ieliwb** [hashbangcode/curl_converter#1]
There seems to be a bug, postman's cURL does not support？

**Comment by philipnorton42** [comment]
Hi ieliwb,
You are right, that is a bug. The command you pasted wasn't extracted correctly and resulted in the header flags being left out.
It turns out the fix was to re-order the way in which the regex is applied to the command. I've added a test that checks for that.
Thanks for reporting! I'll tag a new release with the fix in.

**Comment by ieliwb** [comment]
> Hi ieliwb, You are right, that is a bug. The command you pasted wasn't extracted correctly and resulted in the header flags being left out. It turns out the fix was to re-order the way in which the regex is applied to the command. I've added a test that checks for that. Thanks for reporting! I'll tag a new release with the fix in.

Thanks for fixed. But there is still a bug with post data,  --data-raw is empty


array(11) {
  [0]=>
  string(66) "--location --request POST 'http://fiddle.jshell.net/echo/html/' \
"
  [1]=>
  string(46) "--header 'Origin: http://fiddle.jshell.net' \
"
  [2]=>
  string(44) "--header 'Accept-Encoding: gzip, deflate' \
"
  [3]=>
  string(45) "--header 'Accept-Language: en-US,en;q=0.8' \
"
  [4]=>
  string(165) "--header 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' \
"
  [5]=>
  string(76) "--header 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
"
  [6]=>
  string(25) "--header 'Accept: */*' \
"
  [7]=>
  string(57) "--header 'Referer: http://fiddle.jshell.net/_display/' \
"
  [8]=>
  string(46) "--header 'X-Requested-With: XMLHttpRequest' \
"
  [9]=>
  string(36) "--header 'Connection: keep-alive' \
"
  [10]=>
  string(10) "--data-raw"
}


Can you help me? thanks.

**Comment by philipnorton42** [comment]
Sorry, there was another small issue with the regex, so I've also added a fix for that.

Check out version 1.0.2.
